### ISSUE TITLE
Get rid of VS warning because of CMake

### ISSUE THREAD

**Issue by JiayinCao** [JiayinCao/Tiny-Shading-Language#16]
There is a warning about timestamp of CMake generated files.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8065: Custom build for item "D:\Github\Tiny-Shading-Language\src\core_lib\CMakeLists.txt" succeeded, but specified output "d:\github\tiny-shading-language\_out\src\core_lib\cmakefiles\generate.stamp" has not been created. This may cause incremental build to work incorrectly.
2

However, since this doesn't block me, the priority is very low.

**Comment by Johnnyxy** [comment]
Hi there,
this is a warning issued only when using VS2019 or newer since there where changes in the project handling by Microsoft.
This does not interfere with any processing by CMake or the compiler. Normally a CMake user cannot do anything to avoid this as it is by design.

For further details visit the CMake [issue tracker](https://gitlab.kitware.com/cmake/cmake/-/issues/19737): https://gitlab.kitware.com/cmake/cmake/-/issues/19737

**Comment by JiayinCao** [comment]
Hi Johnnyxy

I appreciate your suggestion.
But I manage to find a way to work around it somehow.
ddc1df37e1fc20c5b8c9e42c6b12c914405be67f

Closing this ticket since it is not a problem anymore.

Thanks

**Comment by Johnnyxy** [comment]
Hm, I am supprised about this ```CALL``` workaround.
Thanks for the suggestion, I will look into it.
